const products = [
  {
    id: "desert-oversized-hoodie",
    name: "Desert Oversized Hoodie",
    category: "Hoodies",
    price: 149,
    currency: "CHF",
    color: "Sand",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Heavy brushed fleece with an oversized silhouette and muted desert tone.",
    fullDescription:
      "Designed for layered city wear, the Desert Oversized Hoodie balances volume, weight and restraint. The fabric feels dense and premium, while the washed sand finish keeps the piece understated and modern.",
    material: "100% cotton, 480 gsm brushed fleece, oversized fit, dropped shoulder",
    drop: "Desert Capsule",
    status: "Featured",
    image: "Sand / Editorial Placeholder",
    imageSecondary: "Texture / Detail Placeholder",
    imageSrc: "assets/img/DesertOversizedHoodie.png",
    imageSecondarySrc: "assets/img/DesertOversizedHoodie.png"
  },
  {
    id: "stone-washed-tee",
    name: "Stone Washed Tee",
    category: "T-Shirts",
    price: 69,
    currency: "CHF",
    color: "Stone",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Boxy heavyweight tee with washed texture and a clean neckline.",
    fullDescription:
      "The Stone Washed Tee is cut with a square body and slightly extended sleeve for a deliberate silhouette. Its subtle surface fade gives the piece depth without losing the clean SUADA edge.",
    material: "100% cotton, heavyweight jersey, boxy cut, garment washed",
    drop: "Desert Capsule",
    status: "Current",
    image: "Stone / Editorial Placeholder",
    imageSecondary: "Back Print / Placeholder",
    imageSrc: "assets/img/StoneWashedTee.png",
    imageSecondarySrc: "assets/img/StoneWashedTee.png"
  },
  {
    id: "dune-utility-jacket",
    name: "Dune Utility Jacket",
    category: "Jackets",
    price: 219,
    currency: "CHF",
    color: "Faded Olive",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Structured outer layer with technical pockets and a dry matte finish.",
    fullDescription:
      "Built as a lightweight statement layer, the Dune Utility Jacket merges utility detailing with a fashion-forward shape. The muted olive tone keeps it grounded while the silhouette stays sharp and directional.",
    material: "Cotton-nylon blend, matte washed finish, relaxed fit, utility pocketing",
    drop: "Desert Capsule",
    status: "Featured",
    image: "Olive / Utility Placeholder",
    imageSecondary: "Pocket Detail / Placeholder",
    imageSrc: "assets/img/DuneUtilityJacket.png",
    imageSecondarySrc: "assets/img/DuneUtilityJacket.png"
  },
  {
    id: "shadow-essential-pants",
    name: "Shadow Essential Pants",
    category: "Pants",
    price: 129,
    currency: "CHF",
    color: "Washed Black",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Wide-leg staple pant with clean drape and subtle structure.",
    fullDescription:
      "These pants are designed to anchor the capsule. The leg falls with intention, the waistband sits comfortably, and the washed black finish gives depth to everyday styling.",
    material: "Cotton twill, enzyme washed, wide straight leg, adjustable hem",
    drop: "Desert Capsule",
    status: "Current",
    image: "Black / Pant Placeholder",
    imageSecondary: "Fit Shot / Placeholder",
    imageSrc: "assets/img/ShadowEssentialsPants.png",
    imageSecondarySrc: "assets/img/ShadowEssentialsPants.png"
  },
  {
    id: "signature-cap",
    name: "Signature Cap",
    category: "Accessories",
    price: 49,
    currency: "CHF",
    color: "Clay",
    sizes: ["One Size"],
    shortDescription: "Minimal six-panel cap with tonal SUADA embroidery.",
    fullDescription:
      "The Signature Cap delivers a quiet finish to the full look. Soft structure, tonal branding and a muted clay shade make it easy to wear across the whole collection.",
    material: "Cotton canvas, soft crown, embroidered logo, adjustable strap",
    drop: "Desert Capsule",
    status: "Current",
    image: "Clay / Cap Placeholder",
    imageSecondary: "Embroidery / Placeholder",
    imageSrc: "assets/img/SignatureCap.png",
    imageSecondarySrc: "assets/img/SignatureCap.png"
  },
  {
    id: "bloodmoon-heavyweight-hoodie",
    name: "Bloodmoon Heavyweight Hoodie",
    category: "Hoodies",
    price: 159,
    currency: "CHF",
    color: "Deep Red",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Dense fleece hoodie cut wide and finished in a dramatic wine red.",
    fullDescription:
      "The Bloodmoon Heavyweight Hoodie carries the darker tone of the archive capsule. It feels substantial on body and creates a strong silhouette with little effort.",
    material: "100% cotton, 500 gsm brushed fleece, oversized fit, washed finish",
    drop: "Bloodmoon Capsule",
    status: "Archive",
    image: "Red / Campaign Placeholder",
    imageSecondary: "Hood Detail / Placeholder",
    imageSrc: "assets/img/BloodmoonHeavyweightHoodie.png",
    imageSecondarySrc: "assets/img/BloodmoonHeavyweightHoodie.png"
  },
  {
    id: "ash-layer-tee",
    name: "Ash Layer Tee",
    category: "T-Shirts",
    price: 72,
    currency: "CHF",
    color: "Ash Grey",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Heavy tee designed for layering with a dry hand feel.",
    fullDescription:
      "The Ash Layer Tee sits between essential and statement. Its cool grey tone and precise proportions give it editorial versatility, especially under outerwear and knit layers.",
    material: "100% cotton, compact jersey, boxy fit, reinforced collar",
    drop: "Bloodmoon Capsule",
    status: "Archive",
    image: "Ash / Layer Placeholder",
    imageSecondary: "Campaign Crop / Placeholder",
    imageSrc: "assets/img/AshLayerTee.png",
    imageSecondarySrc: "assets/img/AshLayerTee.png"
  },
  {
    id: "eclipse-zip-jacket",
    name: "Eclipse Zip Jacket",
    category: "Jackets",
    price: 239,
    currency: "CHF",
    color: "Shadow Grey",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Clean zip jacket with sharp collar line and subtle sheen.",
    fullDescription:
      "A refined outerwear piece from the Bloodmoon archive. The Eclipse Zip Jacket pairs a compact body with a directional collar shape, giving it a quietly elevated presence.",
    material: "Structured nylon blend, satin matte finish, cropped relaxed fit",
    drop: "Bloodmoon Capsule",
    status: "Sold Out",
    image: "Grey / Zip Placeholder",
    imageSecondary: "Collar Detail / Placeholder",
    imageSrc: "assets/img/EclipseZipJacket.png",
    imageSecondarySrc: "assets/img/EclipseZipJacket.png"
  },
  {
    id: "crimson-statement-tee",
    name: "Crimson Statement Tee",
    category: "T-Shirts",
    price: 79,
    currency: "CHF",
    color: "Black / Crimson",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Graphic tee with restrained front branding and deep red artwork.",
    fullDescription:
      "This piece leans more expressive without losing control. The graphic treatment stays sharp and minimal, while the black and crimson contrast pushes the campaign mood forward.",
    material: "100% cotton, heavyweight jersey, boxy fit, screen print",
    drop: "Bloodmoon Capsule",
    status: "Archive",
    image: "Graphic / Placeholder",
    imageSecondary: "Print Detail / Placeholder",
    imageSrc: "assets/img/CrimsonStatementTee.png",
    imageSecondarySrc: "assets/img/CrimsonStatementTee.png"
  },
  {
    id: "void-cargo-pants",
    name: "Void Cargo Pants",
    category: "Pants",
    price: 139,
    currency: "CHF",
    color: "Near Black",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Wide cargo pant with clean utility pockets and structured leg volume.",
    fullDescription:
      "The Void Cargo Pants translate utilitarian cues into a cleaner luxury-streetwear language. Pocket lines stay low-profile while the shape delivers movement and presence.",
    material: "Cotton ripstop, washed black finish, wide fit, utility pockets",
    drop: "Bloodmoon Capsule",
    status: "Sold Out",
    image: "Cargo / Placeholder",
    imageSecondary: "Pocket View / Placeholder",
    imageSrc: "assets/img/VoidCargoPants.png",
    imageSecondarySrc: "assets/img/VoidCargoPants.png"
  },
  {
    id: "canvas-tote",
    name: "Canvas Tote",
    category: "Accessories",
    price: 39,
    currency: "CHF",
    color: "Off-White",
    sizes: ["One Size"],
    shortDescription: "Minimal daily tote with bold SUADA placement and reinforced seams.",
    fullDescription:
      "A clean carry piece designed to complement both capsules. The Canvas Tote uses contrast branding and solid construction to feel considered rather than promotional.",
    material: "Heavy canvas, reinforced handles, screen print logo",
    drop: "Core Essentials",
    status: "Current",
    image: "Canvas / Placeholder",
    imageSecondary: "Logo Detail / Placeholder",
    imageSrc: "assets/img/CanvasTote.png",
    imageSecondarySrc: "assets/img/CanvasTote.png"
  },
  {
    id: "obsidian-rib-tank",
    name: "Obsidian Rib Tank",
    category: "T-Shirts",
    price: 55,
    currency: "CHF",
    color: "Obsidian",
    sizes: ["S", "M", "L", "XL"],
    shortDescription: "Slim rib tank for layering with a dense premium cotton feel.",
    fullDescription:
      "The Obsidian Rib Tank sharpens base-layer styling with a close fit and rich black tone. It is designed for contrast under oversized outer silhouettes.",
    material: "Cotton-elastane rib, close fit, bound neckline",
    drop: "Core Essentials",
    status: "Current",
    image: "Rib / Placeholder",
    imageSecondary: "Layering Shot / Placeholder",
    imageSrc: "assets/img/ObsidianRibTank.png",
    imageSecondarySrc: "assets/img/ObsidianRibTank.png"
  }
];
